### ISSUE TITLE
extionsion.cs missing...

### ISSUE THREAD

**Issue by jeong760** [divinci/khovratovich-equihash-cs#3]
Dears,

What is a content of the **extension.cs** file, which missing from this reference repo?

Regards,
John Ahn

**Comment by divinci** [comment]
Hi John, sorry never noticed that, ill check it out and update when I am at
a PC

**Comment by jeong760** [comment]
Dears,
 
Thank you. 
I want to refer to your code in order to implement a Equihash on CoiniumServ(which programmed by C#) mining pool software. 
 
Regards,
John Ahn
-----Original Message-----

**Comment by divinci** [comment]
@jeong760 John it would be better to use a native implementation, a C# implementation will not be suitable for a miner.

**Comment by jeong760** [comment]
@divinci Yes but I don't know C++. so I want to see how first on C#

**Comment by divinci** [comment]
Hi John, there was nothing in the file, removed from project.
